config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index' 
  post   "favorites/:book_id/create"  => "favorites#create"
  delete "favorites/:book_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :thoughts, length: { maximum: 400 }
  validate  :picture_size

  def feed_comment(book_id)
    Comment.where("book_id = ?", book_id)
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "：5MBより大きい画像はアップロードできません。")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:success] = "本が登録されました！"
      redirect_to root_url
    else
      render 'books/new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "本の情報が更新されました！"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if current_user.admin? || current_user?(@book.user)
      @book.destroy
      flash[:success] = "本が削除されました"
      redirect_to request.referrer == user_url(@book.user) ? user_url(@book.user) : root_url
    else
      flash[:danger] = "他人の本は削除できません"
      redirect_to root_url
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :thoughts, :picture)
  end

  def correct_user
    # 現在のユーザーが更新対象の本を保有しているかどうか確認
    @book = current_user.books.find_by(id: params[:id])
    redirect_to root_url if @book.nil?
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<% @book = book %> 
<li id="book-<%= book.id %>">
  <div class="row">
    <div class="col-md-4">
      <span>
        <%= link_to((image_tag book.picture.thumb200.url), book_path(book.id), class: 'book-picture') if book.picture.url.present? %>
      </span>
      <%= render 'users/favorite_form' %>
    </div>
    <div class="col-md-8 escape-float">
      <h3 class="book-name"><%= link_to book.name, book_path(book) %></h3>
      <div class="book-thoughts "><%= simple_format(book.thoughts) %></div>
      <div class="book-user">reader  <%= link_to book.user.name, user_path(book.user) %></div>
      <div class="row">
        <div class="col-md-6">
          <div class="book-created-at">
            <%= time_ago_in_words(book.created_at) %>前に投稿
          </div>
        </div>
        <% if current_user.admin? || (current_user == book.user) %>
          <div class="col-md-6">
            <%= link_to "削除", book_path(book), method: :delete,
                               data: { confirm: "本当に削除しますか？" } %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/books/_book_form.html.erb
<%= form_with model: @book, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <span class="picture">
    <%= f.label :picture %>　<span class="input-unneed"></span>
    <%= f.file_field :picture, accept: 'image/jpeg,image/png', class: 'form-control', id: 'book_picture' %>
  </span>
  <div class = 'form-group'>
    <%= f.label :name %>　<span class="input-need"></span>
    <%= f.text_field :name, class: 'form-control', id: 'book_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :thoughts %>　<span class="input-unneed"></span>
    <%= f.text_area :thoughts, :size=>"60x10", class: 'form-control', id: 'book_thoughts' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  $('#book_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('アップロードできる画像の最大サイズは5MBです。5MB以下の画像を選択してください');
    }
  });
</script>

app/views/books/edit.html.erb
<% provide(:title, "本の情報編集") %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@book) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <span class="picture">
              <%= f.label :picture %>　<span class="input-unneed"></span>
              <%= f.file_field :picture, accept: 'image/jpeg,image/png', class: 'form-control', id: 'book-picture' %>
              <%= image_tag(@book.picture.thumb400.url) if @book.picture.url.present? %>
              <p></p>
          </span>
          <p></p>
          <div class = 'form-group'>
            <%= f.label :name %>　<span class="input-need"></span>
            <%= f.text_field :name, class: 'form-control', id: 'book_name' %>
          </div>
          <div class = 'form-group'>
            <%= f.label :thoughts %>　<span class="input-unneed"></span>
            <%= f.text_area :thoughts, :size=>"60x10", class: 'form-control', id: 'book_thoughts' %>
          </div>
          <%= f.submit "更新する", class: "btn btn-primary" %>
          <p></p>
          <%= link_to "本を削除する", book_path(@book), method: :delete,
                                      data: { confirm: "本当にこの本を削除してよろしいですか？" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% provide(:title, '本一覧') %>
<div id="fh5co-portfolio">
  <div class="container">
    <% if @search_word.present? %>
      <h3>”<%= @search_word %>”の検索結果：<%= @books.count %>件</h3>
    <% else %>
      <h3>本一覧</h3>
    <% end %>
    <ul class="books">
      <%= render @books %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/books/new.html.erb
<% provide(:title, "本の登録") %>
<div id="fh5co-portfolio">
  <div class="container">
    <h1>本の登録</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= render 'books/book_form' %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, "#{@book.name}") %>
<% @comments  = @book.feed_comment(@book.id) %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="picture">
          <%= link_to((image_tag @book.picture.thumb400.url), book_path(@book.id), class: 'book-picture') if @book.picture.url.present? %>
        </span>
        <%= render 'users/favorite_form' %>
      </div>
      <div class="col-md-8">
        <h2 class="book-name"><%= @book.name %></h2>
        <div class="change-book">
          <% if current_user == @book.user %>
            <%= link_to "編集", edit_book_path(@book), class: 'edit-book' %>　
          <% end %>
          <% if current_user.admin? || (current_user == @book.user) %>
            <%= link_to "削除", book_path(@book), method: :delete, class: 'delete-book',
                                          data: { confirm: "本当に削除しますか？" } %>
          <% end %>
        </div>
        <h4><%= simple_format(@book.thoughts) %></h4>
       </div>
        <div class="comment">
          <%= render "comments/feed_comments" %> 
          <%= render "comments/new" %>
        </div>
      </div>
    </div>
  </div>
</div>