config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :books
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index' 
  post   "favorites/:book_id/create"  => "favorites#create"
  delete "favorites/:book_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2020 CS All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_js.html.erb
<!-- jQuery -->
<%= javascript_include_tag('jquery.min') %>
<!-- jQuery Easing -->
<%= javascript_include_tag('jquery.easing.1.3') %>
<!-- Bootstrap -->
<%= javascript_include_tag('bootstrap.min') %>
<!-- Waypoints -->
<%= javascript_include_tag('jquery.waypoints.min') %>
<!-- Flexslider -->
<%= javascript_include_tag('jquery.flexslider-min') %>
<!-- Main -->
<%= javascript_include_tag('main') %>
<!-- Custom -->
<%= javascript_include_tag('custom') %>

app/views/layouts/_navigation.html.erb
<nav class="fh5co-nav navbar-fixed-top" role="navigation">
  <div class="top-menu">
    <div class="container">
      <div class="row">
        <div class="col-xs-2">
          <div id="fh5co-logo">
            <%= link_to(image_tag("/images/header_logo.jpg", :alt => "header-logo"), root_url, id: 'logo') %>
          </div>
        </div>
        <div class="col-xs-10 text-right menu-1">
          <ul>
            <% if logged_in? %>
              <% if current_user.notification == true %>
                <li class="new_notification header-link">
              <% else %>
                <li class="no_notification header-link">
              <% end %>
              <%= link_to notifications_path do %><span class="fas fa-bell"></i></span> <span></span><% end %>
              </li>
              <li class="header-link">
                <%= link_to favorites_path do %><span class="fas fa-heart"></span> <span></span><% end %>
              </li>
              <li class="has-dropdown">
                <%= link_to current_user do %>
                  <span class="fas fa-book-reader"></span>
                <% end %>
                <ul class="dropdown">
                  <li><%= link_to 'プロフィール', current_user %></li>
                  <li><%= link_to 'ユーザー一覧', users_path %></li>
                  <li><%= link_to 'BOOK TIME？', about_path %></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li class="header-link">

                <%= link_to about_path do %><span class="far fa-question-circle"></i></span> <span></span><% end %>
              </li>
              <li class="header-link">
                <%= link_to signup_path do %><span class="far fa-smile"></i></span> <span></span><% end %>
              </li>
              <li class="header-link btn-cta">
                <%= link_to login_path do %><span> ログイン</span><% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="読んだ本に関して記憶に残しておきたいことを共有するサービスです。本から得た知識をアウトプットして写真で結果を記録する、そこにコメントをしたり、お気に入りに登録することもできます。" />
<meta name="keywords" content="BOOK TIME, 記録, SNS" />
<link rel="shortcut icon" href="/images/favicon.ico">

<!-- Facebook and Twitter integration -->
<meta property="og:title" content=""/>
<meta property="og:image" content=""/>
<meta property="og:url" content=""/>
<meta property="og:site_name" content=""/>
<meta property="og:description" content=""/>
<meta name="twitter:title" content="" />
<meta name="twitter:image" content="" />
<meta name="twitter:url" content="" />
<meta name="twitter:card" content="" />

<link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>

app/views/layouts/_search.html.erb
<div class="row">
  <%= search_form_for @q do |f| %>
    <div class="col-md-10">
      <div class='form-group'>
        <%= f.search_field :name_cont, placeholder: "本のタイトルまたは著者名で検索", class: 'form-control font-awesome' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class='form-group'>
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="fh5co-loader"></div>
        <div id="page">
          <%= render 'layouts/navigation' %>
          <div id="fh5co-wireframe">
            <div class="container">
              <% flash.each do |message_type, message| %>
                <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
              <% end %>
              <%= render 'layouts/search' if logged_in? %>
            </div>
          </div>
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
        <div class="gototop js-top">
          <a href="#" class="js-gotop"><i class="fas fa-arrow-up"></i></a>
        </div>
        <%= render 'layouts/js' %>
  </body>
</html>